export {Navbar} from './common/navbar/Navbar'
export {Footer} from './common/footer/Footer'
export {SectionHeader} from './common/sectionHeader/SectionHeader'
export {PageHeader} from './common/pageHeader/PageHeader'
export {MultiSwiper} from './common/multiSwiper/MultiSwiper'
export {Button} from '@/components/common/button/Button'

export {HeroSection} from '@/components/section/hero/HeroSection'
export {OurPartnersSection} from '@/components/section/ourPartners/OurPartnersSection'
export {NewsSection} from '@/components/section/news/NewsSection'
export {LocationsSection} from '@/components/section/locations/LocationsSection'
